%% Function for printing the status
function printStatus(left, right)
%	fprintf(['ld: ' num2str(left.d) ', rd: ' num2str(right.d) ...
%       '\t\tlVirt: ' num2str(left.dVirt) ', rVirt: ' num2str(right.dVirt) ...
%       '\t\tlSpeed: ' num2str(left.v) ', rSpeed: ' num2str(right.v) ...
%       '\t\tldx: ' num2str(left.dx) ', rdx: ' num2str(right.dx) ...
%       '\t\tldt: ' num2str(left.dt) ', rdt: ' num2str(right.dt) '\n']);
	fprintf('ld: %0.2f, rd: %0.2f\t\tlSpeed: %0.2f, rSpeed %0.2f\t\tldx: %d, rdx: %d\t\tldt: %0.3f, rdt: 0.3f', left.d, right.d, left.v, right.v, left.dx, right.dx, left.dt, right.dt);
end